### ISSUE TITLE
Able to support multiple reporters

### ISSUE THREAD

**Issue by mengchen2** [krakenjs/nemo#15]
Right now, only one reporter supported to be used at same time.
If we config the reporter like following, only Xunit report will get generated.
"mocha": {
"timeout": 180000,
"reporter": "mochawesome",
"reporter": "xunit",
"retries": 0,
"require": "babel-register",
"grep": "argv:grep"
},
xunit report is about publish the result to Jenkins.
json report is easy to feed database.

reference link: https://github.com/mochajs/mocha/pull/2184/files

**Comment by grawk** [comment]
This is not a feature in mocha and thus no way to take advantage of it in nemo.
