### ISSUE TITLE
Make sure this.nemo available in all mocha lifecycle functions 

### ISSUE THREAD

**Issue by grawk** [krakenjs/nemo#19]
Currently `this.nemo` is available in the test (`it`) context and the `beforeEach` context. Make the nemo object available in all mocha lifecycle functions:
`before`
`beforeEach`
`after`
`afterEach`

**Comment by nikulkarni** [comment]
Hey so I looked at the code and currently `this.nemo` is available in `beforeEach`, `afterEach` and `after`.  Its only not available in `before`. Ideally `nemo` should be a brand new object for every test and it shouldn't be shared across tests. Therefore I am not sure if we should set it up in `before`, currently its set correctly in `beforeEach`.  Do we have a use case that I'm missing where its needed in `before`?
