### ISSUE TITLE
[Feature] Default logging behavior

### ISSUE THREAD

**Issue by maxuuell** [krakenjs/nemo#2]
Will there be a default logging behavior?  I found that, while writing and testing tests, I would get zero feedback from nemo/nemo-runner.  A default logger would be nice.  If you made it lightly configurable, if only just to surface errors from nemo, and not necessarily from what you are testing, that would be very helpful.  If someone wanted to, they could easily turn it off completely with `debugger: false`.

**Comment by grawk** [comment]
Hi @maxuuell. Appreciate the feedback. I hear your (and others) concerns about this so let me look at the various places nemo is catching errors and see if there are any key error handlers which should output by default.

Also with respect to having a more straightforward `debugger` flag in the config, let me look at how easily that may be accomplished. Stay tuned please.

**Comment by grawk** [comment]
Here's what I've got:
https://github.com/krakenjs/nemo/pull/4

You can add the `-L` flag to the CLI with either `info` or `error`

This is much simpler than the current implementation, though not exactly what you asked for.

**Comment by grawk** [comment]
Hi @maxuuell I've published this in `v4.1.0` can you please confirm and close this issue when you get a chance?

**Comment by grawk** [comment]
@maxuuell we've got default error logging merged into master now: https://github.com/krakenjs/nemo/pull/7

Just need to publish.

**Comment by grawk** [comment]
@maxuuell this is published in `v4.2.0` and up. Can you please confirm behavior?

**Comment by maxuuell** [comment]
Confirmed behavior.  This is very helpful.  Thank you.
