### ISSUE TITLE
option to quit driver after every test - it()

### ISSUE THREAD

**Issue by sairamnutheti** [krakenjs/nemo#3]
Nemo runner should allow users to quit the driver if they want after every test. For example in afterEach hook method. Currently deleting cookies in afterEach would not solve this problem. It is still using the previous login information

**Comment by grawk** [comment]
I've refactored the programmatic mocha code here:
https://github.com/krakenjs/nemo/pull/9

This should make it easier to add this request as a feature enhancement.

**Comment by grawk** [comment]
This is resolved by the `driverPerTest` feature released in `v4.4.1`
