### ISSUE TITLE
What do you mean parallel?

### ISSUE THREAD

**Issue by sainianubhav** [krakenjs/nemo#35]
What do you mean parallel? Is it really parallel, as in two threads, how? Or just asynchronous?

```
    -F, --file                   run parallel by file
    -D, --data                run parallel by data
```

**Comment by grawk** [comment]
Nemo uses [`threads`](https://www.npmjs.com/package/threads) and [`async.parallelLimit`](https://caolan.github.io/async/parallelLimit.js.html) to run in parallel. Please see:
https://github.com/krakenjs/nemo/blob/master/lib/master.js
