### ISSUE TITLE
Is this known feature or a bug?

### ISSUE THREAD

**Issue by sainianubhav** [krakenjs/nemo#37]
I can invoke tests `npm run nemo -- -G '#phone #add #US'` and it runs two tests only for US.

I can invoke tests `npm run nemo -- -G '#phone #add #US #HOME'` and it runs just one test only for US and HOME.

```

['AU', 'BR', 'ES', 'FR', 'GB', 'GB', 'IN', 'MX', 'US'].forEach(CC => {
	['HOME', 'WORK'].forEach(t => {
		describe(`#phone #add #${CC} #${t}`, function () {
			it(`should test adding of phone of a specific type`, async function () {
				await add.default(this.nemo, phoneInfo.types[CC][t], CC);
			});
		});
	});
});

```

I want to know if A) This is a known feature and that it will stay. B) If its a bug and tests shouldn't be written like it.

I think when nemo goes to build metadata about tests, it somehow parses all the specs and just don't run them. Is that so? It runs later, after reading command line arguments.

**Comment by grawk** [comment]
The behavior seems correct based on the code. What is the expected behavior?

**Comment by sainianubhav** [comment]
This is a feature then.
