### ISSUE TITLE
Can we have a switch for zero exit code when tests fail

### ISSUE THREAD

**Issue by zzhengjian** [krakenjs/nemo#59]
Can we have a switch for non-zero exit code for failing tests? This cause the jenkins job failing, and actually for me, I only need to view tests run info in the automation report, so I want the jenkins job is always successful.

**Comment by zzhengjian** [comment]
When you have e2e test cases, it's quite normal to have failed tests due to many reasons, so compare to unit test, we may need to be more tolerate for this.

**Comment by grawk** [comment]
Hi @zzhengjian that makes sense. I'm not sure when I can get to it. If someone can contribute a PR it might be quicker.

**Comment by zzhengjian** [comment]
@grawk Hi, I create a PR https://github.com/krakenjs/nemo/pull/64, please take a review.

**Comment by grawk** [comment]
closed by #64
